### ISSUE TITLE
inefficient algorithm

### ISSUE THREAD

**Issue by jej2660** [shark1964/htdocs#2]
https://github.com/shark1964/htdocs/blob/9538ca405e1e29e50ac1844a554b8830c7099f66/compareData.php#L21

디비 전체를 긁어와서 비교 하는 것 같은데 유저수가 많아지면 상당히 느려지게 됨

오버헤드를 해결하기 위해 id 를 긁어오는 것 필요

**Comment by KRhound** [comment]
test file을 실수로 올렸습니다.
