### ISSUE TITLE
db connection issue

### ISSUE THREAD

**Issue by jej2660** [shark1964/htdocs#3]
https://github.com/shark1964/htdocs/blob/9538ca405e1e29e50ac1844a554b8830c7099f66/main/main.php#L108

db connection 이 필요할 떄마다 새로 하지말고 하나의 함수나 페이지에 con 을 리턴해주는 로직을 추가해놓고 페이지에서 include 나 ㅇimport 해서 사용하면 코드가 효율적임

예를 들어서 db 이름이나 패스워드가 바뀌게 되면 모든 페이지에서 비밀번호를 바꿔야 하는 이슈가 생김 하나만 바꿔도 되도록 설정

**Comment by shark1964** [comment]
connect_db.php
<?php
  $connect = mysqli_connect("127.0.0.1", "root", "3733990", "user_db") or die("connect failed");
  $connect->set_charset("utf8");
?>

위 php파일을 필요로 하는.php
include("../connect_db.php");

**Comment by shark1964** [comment]
connect_db.php
<?php
  $connect = mysqli_connect("127.0.0.1", "root", "3733990", "user_db") or die("connect failed");
  $connect->set_charset("utf8");
?>

위 php파일을 필요로 하는.php
include("../connect_db.php");

**Comment by KRhound** [comment]
<...>
connect_db.php
<?php
  $connect = mysqli_connect("127.0.0.1", "root", "3733990", "user_db") or die("connect failed");
  $connect->set_charset("utf8");
?>

위 php파일을 필요로 하는.php
include("../connect_db.php");
