### ISSUE TITLE
sql injection issue

### ISSUE THREAD

**Issue by jej2660** [shark1964/htdocs#4]
https://github.com/shark1964/htdocs/blob/9538ca405e1e29e50ac1844a554b8830c7099f66/login/login_action.php#L13

sql injection

**Comment by KRhound** [comment]
<기존 코드>
$sql = "select * from myguests where id='$id'"; 

<변경 후>
$sql = sprintf("select * from myguests where id='%s';", addslashes($id));

변수 id의 입력값을 문자형으로 받고, id 변수의 특수문자를 일반 문자로 변환하는 방식의 코드로 보완하였습니다.

**Comment by jej2660** [comment]
FIX
