### ISSUE TITLE
password need hash function

### ISSUE THREAD

**Issue by jej2660** [shark1964/htdocs#5]
https://github.com/shark1964/htdocs/blob/9538ca405e1e29e50ac1844a554b8830c7099f66/login/login_action.php#L19

패스워드를 노멀하게 저장하면 안됨

hash 함수를 넣어서 저장해야됨
해쉬 함수에 대해 공부~

**Comment by KRhound** [comment]
https://github.com/shark1964/htdocs/commit/d696e4edbd43f0ccd068bf075bfef2cbaa0450ed

수정했습니다.
